const ActionTypes = {
  UPDATE_USERS: 'UPDATE_USERS',
  GET_USERS: 'GET_USERS',
  ADD_USERS: 'ADD_USERS',
  DEL_USERS: 'DEL_USERS',
  GET_USERS_SUCCEED: 'GET_USERS_SUCCEED',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  ADD_USERS_SUCCEED: 'ADD_USERS_SUCCEED',
  ADD_USERS_FAILED: 'ADD_USERS_FAILED',
  UPDATE_USERS_SUCCEED: 'UPDATE_USERS_SUCCEED',
  UPDATE_USERS_FAILED: 'UPDATE_USERS_FAILED',
  DEL_USERS_SUCCEED: 'DEL_USERS_SUCCEED',
  DEL_USERS_FAILED: 'DEL_USERS_FAILED',
  // ini untuk auth
  LOGIN: 'LOGIN',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TRY_AGAIN: 'TRY_AGAIN',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

export default ActionTypes;
